services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_PATH: /etc/todos/todo.db   # Match the volume mount
    volumes:
      - todo-db:/etc/todos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped   # Auto-restart unless you stop it manually

volumes:
  todo-db:
