name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run all Jest tests except sqlite persistence
      - name: Run Jest tests (skip sqlite persistence)
        run: yarn jest --runInBand --testPathIgnorePatterns=spec/persistence/sqlite.spec.js
