name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Jest cache
        uses: actions/cache@v4
        with:
          path: .jest-cache
          key: ${{ runner.os }}-jest-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-jest-

      # Run full suite on push to main
      - name: Run full Jest tests (skip sqlite persistence)
        if: github.event_name == 'push'
        run: yarn jest --ci --cache --cacheDirectory=.jest-cache --testPathIgnorePatterns=spec/persistence/sqlite.spec.js

      # Run only changed tests on pull requests
      - name: Run Jest only for changed files (skip sqlite persistence)
        if: github.event_name == 'pull_request'
        run: |
          yarn jest --ci --cache --cacheDirectory=.jest-cache \
            --testPathIgnorePatterns=spec/persistence/sqlite.spec.js \
            --findRelatedTests $(git diff --name-only origin/main...HEAD)
